site_name: 'Nice PHP Framework'
site_url: http://niceframework.com
repo_url: https://github.com/nice-php/framework
pages:
  - ['introduction.md', 'Introduction']
  - ['contributing.md', 'Contributing']
  - ['getting-started/installation.md', 'Getting Started', 'Installation']
  - ['getting-started/your-first-app.md', 'Getting Started', 'Your First App']
  - ['getting-started/routing.md', 'Getting Started', 'Routing']
  - ['getting-started/logging.md', 'Getting Started', 'Logging']
  - ['getting-started/caching.md', 'Getting Started', 'Caching']
  - ['getting-started/middlewares.md', 'Getting Started', 'Middlewares']
  - ['extensions/sessions.md', 'Extensions', 'Sessions']
  - ['extensions/security.md', 'Extensions', 'Security']
  - ['extensions/cache.md', 'Extensions', 'Cache']
  - ['extensions/log.md', 'Extensions', 'Log']
  - ['templating/php.md', 'Templating', 'Symfony 2']
  - ['templating/twig.md', 'Templating', 'Twig']
  - ['templating/plates.md', 'Templating', 'Plates']
  - ['extensions/doctrine-dbal.md', 'Doctrine', 'DBAL']
  - ['extensions/doctrine-orm.md', 'Doctrine', 'ORM']
  - ['extensions/doctrine-key-value.md', 'Doctrine', 'Key-Value Store']
  - ['extensions/doctrine-odm.md', 'Doctrine', 'ODM']
  - ['cookbook/introduction.md', 'Cookbook', 'Introduction']
  - ['cookbook/custom-extensions.md', 'Cookbook', 'Custom Extensions']
  - ['cookbook/compiler-passes.md', 'Cookbook', 'Compiler Passes']
  - ['cookbook/custom-route-collector.md', 'Cookbook', 'Custom Route Collector']
  - ['cookbook/config-cache.md', 'Cookbook', 'Using ConfigCache']
